services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    ports:
      - "3000:5000" # host:container port
    depends_on:
      db: # контейнер app запускается после запуска контейнера db
        condition: service_healthy # если контейнер db доступен
      redis:
        condition: service_healthy
    environment:
      - "DB_URL=postgresql://postgres:postgres@db:5432/flask_db"
      - "REDIS_URL=redis://redis:6379/0"
      - "REDIS_HOST=redis"
    volumes:
      - .:/app # монтирование текущего каталога внутри контейнера
    restart: unless-stopped # перезапуск контейнера если он умирает
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    
  test:
    build:
      context: .
      dockerfile: docker/Dockerfile.test
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - "FLASK_ENV=testing"
      - "DB_URL=postgresql://postgres:postgres@db:5432/flask_db_test"
      - "REDIS_URL=redis://redis:6379/1"
      - "REDIS_HOST=redis"
    volumes:
      - .:/app
      - test-results:/app/test-results
    restart: unless-stopped

  db:
    image: postgres:13.1-alpine
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=flask_db"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck: # проверка доступности БД
      test: ["CMD-SHELL", "pg_isready -U postgres"] # команда проверки доступности БД
      interval: 5s # проверять каждые 5 секунд
      timeout: 5s # проверять не более 5 секунд
      retries: 5 # проверять не более 5 раз
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/var/lib/redis/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  redisdata:
    driver: local
  pgdata:
    driver: local
  test-results:
    driver: local