services:
  test:
    build:
      context: .
      dockerfile: docker/Dockerfile.test
    environment:
      - FLASK_ENV=testing
      - DB_URL=postgresql://postgres:postgres@db:5432/flask_db_test
      - REDIS_URL=redis://redis:6379/1
      - REDIS_HOST=redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - test-results:/app/test-results
    command: >
      sh -c "pytest --cov=app --cov-report=term-missing --cov-report=xml:/app/test-results/coverage.xml"

  db:
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flask_db_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  test-results: