services:
  app:
    build: .
    ports:
      - "3000:5000" # host:container port
    depends_on:
      db: # контейнер app запускается после запуска контейнера db
        condition: service_healthy # если контейнер db доступен
      redis:
        condition: service_healthy
    environment: # переменные окружения
      - "DB_URL=postgresql://postgres:postgres@db:5432/flask_db"
      - "REDIS_URL=redis://redis:6379/0"
      - "REDIS_HOST=redis" # имя контейнера redis
    volumes: # монтирование директории внутри контейнера
      - .:/app # монтирование текущего каталога внутри контейнера
    restart: unless-stopped # перезапуск контейнера если он умирает

  db:
    image: postgres:13.1-alpine
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres" # логин пользователя для подключения к БД
      - "POSTGRES_PASSWORD=postgres" # пароль пользователя
      - "POSTGRES_DB=flask_db" # имя БД
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck: # проверка доступности БД
      test: ["CMD-SHELL", "pg_isready -U postgres"] # команда проверки доступности БД
      interval: 5s # проверять каждые 5 секунд
      timeout: 5s # проверять не более 5 секунд
      retries: 5 # проверять не более 5 раз
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/var/lib/redis/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  redisdata:
    driver: local
  pgdata:
    driver: local