# Test Dockerfile
FROM python:3.9-alpine AS builder
WORKDIR /app
RUN apk add --update --no-cache postgresql-dev gcc python3-dev musl-dev
COPY requirements.txt .
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /app/wheels -r requirements.txt

FROM python:3.9-alpine AS test
RUN apk add --update --no-cache libpq curl
RUN adduser -D testuser
WORKDIR /app
COPY --from=builder /app/wheels /wheels
COPY --from=builder /app/requirements.txt .
RUN pip install --no-cache /wheels/* && rm -rf /wheels && rm -rf requirements.txt
COPY . .
RUN chown -R testuser:testuser /app
USER testuser
CMD ["pytest", "--cov=app", "--cov-report=term-missing"]